### ISSUE TITLE
 Introduction/Warm up/Finish the game

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/kotlin-onboarding-introduction#154]
Tests are bad - said Correct for wrong fun safeUserInput(wordLength: Int, alphabet: String) {
    println("Please input your guess. It should be of length $wordLength, and each symbol should be from the alphabet: $alphabet.")
    val input = safeReadLine() - (function is not done yet)

**Comment by Daoortor** [comment]
Input validation is not part of the task in newer versions of the course, so this issue is obsolete.
